# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "forums", :force => true do |t|
    t.column "name",          :string,   :limit => 64
    t.column "administrator", :string,   :limit => 20
    t.column "created_on",    :datetime
  end

  create_table "messages", :force => true do |t|
    t.column "title",      :string,   :limit => 64
    t.column "author",     :string,   :limit => 20
    t.column "created_on", :datetime
    t.column "email",      :string,   :limit => 40
    t.column "message",    :text
    t.column "forum_id",   :integer
  end

  create_table "users", :force => true do |t|
    t.column "name",     :string, :limit => 11
    t.column "password", :string
  end

end
